In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# CSV
import csv

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score

import sklearn
from imblearn.pipeline import Pipeline
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.compose import ColumnTransformer 
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, make_scorer

from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import LinearSVC

import math
from sklearn.metrics import mean_squared_error

# import xgboost as xgb
# from lightgbm import LGBMClassifier

# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Flatten
# from tensorflow.keras.layers import Dropout
# from tensorflow.keras.layers import Dense
# from tensorflow.keras.optimizers import Adam
# import tensorflow as tf
# from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

# Import the SMOTE-NC
from imblearn.over_sampling import SMOTENC

### Read from telco_churn_cleaned.csv

In [2]:
customer_df = pd.read_csv('telco_churn_cleaned.csv')

In [3]:
customer_df

SeniorCitizen  Partner  Dependents    tenure  MultipleLines  \
0                 0        1           0  0.013889              0   
1                 0        0           0  0.472222              0   
2                 0        0           0  0.027778              0   
3                 0        0           0  0.625000              0   
4                 0        0           0  0.027778              0   
...             ...      ...         ...       ...            ...   
7038              0        1           1  0.333333              1   
7039              0        1           1  1.000000              1   
7040              0        1           1  0.152778              0   
7041              1        1           0  0.055556              1   
7042              0        0           0  0.916667              0   

      OnlineSecurity  OnlineBackup  DeviceProtection  TechSupport  \
0                  0             1                 0            0   
1                  1             0                 1            0   
2                  1             1                 0            0   
3                  1             0                 1            1   
4                  0             0                 0            0   
...              ...           ...               ...          ...   
7038               1             0                 1            1   
7039               0             1                 1            0   
7040               1             0                 0            0   
7041               0             0                 0            0   
7042               1             0                 1            1   

      StreamingTV  ...  internet_service_dsl  internet_service_fiber_optic  \
0               0  ...                     1                             0   
1               0  ...                     1                             0   
2               0  ...                     1                             0   
3               0  ...                     1                             0   
4               0  ...                     0                             1   
...           ...  ...                   ...                           ...   
7038            1  ...                     1                             0   
7039            1  ...                     0                             1   
7040            0  ...                     1                             0   
7041            0  ...                     0                             1   
7042            1  ...                     0                             1   

      internet_service_no  contract_month_to_month  contract_one_year  \
0                       0                        1                  0   
1                       0                        0                  1   
2                       0                        1                  0   
3                       0                        0                  1   
4                       0                        1                  0   
...                   ...                      ...                ...   
7038                    0                        0                  1   
7039                    0                        0                  1   
7040                    0                        1                  0   
7041                    0                        1                  0   
7042                    0                        0                  0   

      contract_two_year  payment_method_bank_transfer  \
0                     0                             0   
1                     0                             0   
2                     0                             0   
3                     0                             1   
4                     0                             0   
...                 ...                           ...   
7038                  0                             0   
7039                  0                             0   
7040                 

## Train-test split

In [4]:
X = customer_df.drop(columns={'Churn'})
y = customer_df['Churn']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 424)

## Decision Tree Base Classifier

In [6]:
dt_clf = DecisionTreeClassifier()  
dt_clf.fit(X_train, y_train)

dt_predictions = dt_clf.predict(X_test)

In [7]:
dt_conf_matrix = confusion_matrix(y_test, dt_predictions)
dt_tn = dt_conf_matrix[0][0]
dt_fn = dt_conf_matrix[1][0]
dt_tp = dt_conf_matrix[1][1]
dt_fp = dt_conf_matrix[0][1]
print(dt_tn)
print(dt_fn)
print(dt_tp)
print(dt_fp)

857
172
174
206


In [8]:
dt_accuracy = (dt_tp + dt_tn) / (dt_tp + dt_tn + dt_fp + dt_fn)
dt_precision = dt_tp / (dt_tp + dt_fp)
dt_recall = dt_tp / (dt_tp + dt_fn)
dt_f1_score = 2 * ((dt_precision * dt_recall) / (dt_precision + dt_recall))

print('Decision Tree Accuracy Score: ' + str(dt_accuracy))
print('Decision Tree Precision Score: ' + str(dt_precision))
print('Decision Tree Recall Score: ' + str(dt_recall))
print('Decision Tree F1-Score: ' + str(dt_f1_score))
print(f"RMSE for KNN: {math.sqrt(mean_squared_error(y_test,dt_predictions))}")

Decision Tree Accuracy Score: 0.7317246273953159
Decision Tree Precision Score: 0.45789473684210524
Decision Tree Recall Score: 0.5028901734104047
Decision Tree F1-Score: 0.47933884297520657
RMSE for KNN: 0.517953060232956


## Random Forest Base Classifier

In [9]:
model = RandomForestClassifier()

#Fit the training feature Xs and training label Ys
model.fit(X_train, y_train)

#Use the trained model to predict the test data
y_pred = model.predict(X_test)

# Find the confusion matrix of the result
cm = confusion_matrix(y_test, y_pred)
print(cm)

# Find the accuracy and F1 score of the result
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
rmse = math.sqrt(mean_squared_error(y_test,y_pred))

# Find the accuracy and F1 score of the result
print('Accuracy: ' + str(accuracy))
print('Precision: ' + str(precision))
print('Recall: ' + str(recall))
print('F1: ' + str(f1))
print('RMSE: ' + str(rmse))

[[960 103]
 [183 163]]
Accuracy: 0.7970191625266146
Precision: 0.6127819548872181
Recall: 0.47109826589595377
F1: 0.5326797385620915
RMSE: 0.45053394708210986


## Naive Bayes Base Classifier 

In [10]:
from sklearn.naive_bayes import GaussianNB

#Initialize or define the model
nb = GaussianNB()

#Fit the training feature Xs and training label Ys
nb.fit(X_train, y_train)

#Use the trained model to predict the test data
predictions_nb= nb.predict(X_test)

#Find the confusion matrix of the result
cm = confusion_matrix(y_test, predictions_nb)
print(cm)

#Print the accuracy, precision, recall, and F1 score of the result
print(f"Accuracy for Naive Bayes: {accuracy_score(y_test, predictions_nb)}")
print(f"Precision for Naive Bayes: {precision_score(y_test, predictions_nb)}")
print(f"Recall for Naive Bayes: {recall_score(y_test, predictions_nb)}")
print(f"F1-Score for Naive Bayes: {f1_score(y_test, predictions_nb)}")

[[782 281]
 [ 73 273]]
Accuracy for Naive Bayes: 0.7487579843860894
Precision for Naive Bayes: 0.4927797833935018
Recall for Naive Bayes: 0.7890173410404624
F1-Score for Naive Bayes: 0.6066666666666667


## Logistic Regression Base Classifier

In [13]:
logreg = LogisticRegression()

logreg.fit(X_train, y_train)
predictions_logreg = logreg.predict(X_test)
cm_logreg = confusion_matrix(y_test, predictions_logreg)
rmse = math.sqrt(mean_squared_error(y_test,predictions_logreg))

#Print the accuracy, precision, recall, and F1 score of the result
print(f"Confusion Matrix for Logistic Regression: {cm_logreg}")
print(f"Accuracy for Logistic Regression: {accuracy_score(y_test, predictions_logreg)}")
print(f"Precision for Logistic Regression: {precision_score(y_test, predictions_logreg)}")
print(f"Recall for Logistic Regression: {recall_score(y_test, predictions_logreg)}")
print(f"F1-Score for Logistic Regression: {f1_score(y_test, predictions_logreg)}")
print('RMSE: ' + str(rmse))

Confusion Matrix for Logistic Regression: [[952 111]
 [154 192]]
Accuracy for Logistic Regression: 0.8119233498935415
Precision for Logistic Regression: 0.6336633663366337
Recall for Logistic Regression: 0.5549132947976878
F1-Score for Logistic Regression: 0.5916795069337443
RMSE: 0.4336780489100855


## SVM Base Classifier

In [12]:
from datetime import datetime

from sklearn.svm import LinearSVC

#Your code here. The following comments are just for your reference

#ADDED MYSELF
start=datetime.now()
#END

#Initialize or define the model
linearSVC_svm = LinearSVC()

#Fit the training feature Xs and training label Ys
linearSVC_svm.fit(X_train, y_train)

#Use the trained model to predict the test data
linearSVC_svm_pred = linearSVC_svm.predict(X_test)

#Find the confusion matrix of the result
print('Confusion Matrix:')
print(confusion_matrix(y_test, linearSVC_svm_pred))

#Print the accuracy, precision, recall, and F1 score of the result
# print('Accuracy:')
# print(linearSVC_svm.score(X_test, y_test))
linearSVC_svm_accuracy = accuracy_score(y_test, linearSVC_svm_pred)
print('linearSVC Accuracy: ' + str(linearSVC_svm_accuracy))

linearSVC_svm_precision = precision_score(y_test, linearSVC_svm_pred)
print('linearSVC Precision: ' + str(linearSVC_svm_precision))

linearSVC_svm_recall = recall_score(y_test, linearSVC_svm_pred)
print('linearSVC Recall: ' + str(linearSVC_svm_recall))

linearSVC_svm_f1 = f1_score(y_test, linearSVC_svm_pred)
print('linearSVC F1: ' + str(linearSVC_svm_f1))

print('Time taken:')
print(datetime.now()-start)

Confusion Matrix:
[[951 112]
 [155 191]]
linearSVC Accuracy: 0.8105039034776437
linearSVC Precision: 0.6303630363036303
linearSVC Recall: 0.5520231213872833
linearSVC F1: 0.588597842835131
Time taken:
0:00:00.077400
